// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: quick_start.proto

package content_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuickStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Title             string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Slug              string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug"`
	Description       string `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	DocumentationLink string `protobuf:"bytes,5,opt,name=documentation_link,json=documentationLink,proto3" json:"documentation_link"`
	VideoLink         string `protobuf:"bytes,6,opt,name=video_link,json=videoLink,proto3" json:"video_link"`
	CreatedAt         string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt         string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *QuickStart) Reset() {
	*x = QuickStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quick_start_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuickStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickStart) ProtoMessage() {}

func (x *QuickStart) ProtoReflect() protoreflect.Message {
	mi := &file_quick_start_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickStart.ProtoReflect.Descriptor instead.
func (*QuickStart) Descriptor() ([]byte, []int) {
	return file_quick_start_proto_rawDescGZIP(), []int{0}
}

func (x *QuickStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuickStart) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuickStart) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *QuickStart) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuickStart) GetDocumentationLink() string {
	if x != nil {
		return x.DocumentationLink
	}
	return ""
}

func (x *QuickStart) GetVideoLink() string {
	if x != nil {
		return x.VideoLink
	}
	return ""
}

func (x *QuickStart) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QuickStart) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type QuickStartList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32         `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	Items []*QuickStart `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (x *QuickStartList) Reset() {
	*x = QuickStartList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quick_start_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuickStartList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickStartList) ProtoMessage() {}

func (x *QuickStartList) ProtoReflect() protoreflect.Message {
	mi := &file_quick_start_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickStartList.ProtoReflect.Descriptor instead.
func (*QuickStartList) Descriptor() ([]byte, []int) {
	return file_quick_start_proto_rawDescGZIP(), []int{1}
}

func (x *QuickStartList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QuickStartList) GetItems() []*QuickStart {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_quick_start_proto protoreflect.FileDescriptor

var file_quick_start_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x12, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x59, 0x0a, 0x0e, 0x51,
	0x75, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quick_start_proto_rawDescOnce sync.Once
	file_quick_start_proto_rawDescData = file_quick_start_proto_rawDesc
)

func file_quick_start_proto_rawDescGZIP() []byte {
	file_quick_start_proto_rawDescOnce.Do(func() {
		file_quick_start_proto_rawDescData = protoimpl.X.CompressGZIP(file_quick_start_proto_rawDescData)
	})
	return file_quick_start_proto_rawDescData
}

var file_quick_start_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quick_start_proto_goTypes = []any{
	(*QuickStart)(nil),     // 0: content_service.QuickStart
	(*QuickStartList)(nil), // 1: content_service.QuickStartList
}
var file_quick_start_proto_depIdxs = []int32{
	0, // 0: content_service.QuickStartList.items:type_name -> content_service.QuickStart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quick_start_proto_init() }
func file_quick_start_proto_init() {
	if File_quick_start_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quick_start_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*QuickStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quick_start_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*QuickStartList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quick_start_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quick_start_proto_goTypes,
		DependencyIndexes: file_quick_start_proto_depIdxs,
		MessageInfos:      file_quick_start_proto_msgTypes,
	}.Build()
	File_quick_start_proto = out.File
	file_quick_start_proto_rawDesc = nil
	file_quick_start_proto_goTypes = nil
	file_quick_start_proto_depIdxs = nil
}
