// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: resource_link.proto

package content_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Title         string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Link          string  `protobuf:"bytes,3,opt,name=link,proto3" json:"link"`
	ResourceId    string  `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id"`
	ResourceTitle string  `protobuf:"bytes,5,opt,name=resource_title,json=resourceTitle,proto3" json:"resource_title"`
	CreatedAt     string  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Size          float32 `protobuf:"fixed32,8,opt,name=size,proto3" json:"size"`
}

func (x *ResourceLink) Reset() {
	*x = ResourceLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLink) ProtoMessage() {}

func (x *ResourceLink) ProtoReflect() protoreflect.Message {
	mi := &file_resource_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLink.ProtoReflect.Descriptor instead.
func (*ResourceLink) Descriptor() ([]byte, []int) {
	return file_resource_link_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ResourceLink) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceLink) GetResourceTitle() string {
	if x != nil {
		return x.ResourceTitle
	}
	return ""
}

func (x *ResourceLink) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResourceLink) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ResourceLink) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ResourceLinkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32           `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	Items []*ResourceLink `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (x *ResourceLinkList) Reset() {
	*x = ResourceLinkList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLinkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLinkList) ProtoMessage() {}

func (x *ResourceLinkList) ProtoReflect() protoreflect.Message {
	mi := &file_resource_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLinkList.ProtoReflect.Descriptor instead.
func (*ResourceLinkList) Descriptor() ([]byte, []int) {
	return file_resource_link_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLinkList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResourceLinkList) GetItems() []*ResourceLink {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_resource_link_proto protoreflect.FileDescriptor

var file_resource_link_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x5d, 0x0a, 0x10, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_link_proto_rawDescOnce sync.Once
	file_resource_link_proto_rawDescData = file_resource_link_proto_rawDesc
)

func file_resource_link_proto_rawDescGZIP() []byte {
	file_resource_link_proto_rawDescOnce.Do(func() {
		file_resource_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_link_proto_rawDescData)
	})
	return file_resource_link_proto_rawDescData
}

var file_resource_link_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_link_proto_goTypes = []any{
	(*ResourceLink)(nil),     // 0: content_service.ResourceLink
	(*ResourceLinkList)(nil), // 1: content_service.ResourceLinkList
}
var file_resource_link_proto_depIdxs = []int32{
	0, // 0: content_service.ResourceLinkList.items:type_name -> content_service.ResourceLink
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_link_proto_init() }
func file_resource_link_proto_init() {
	if File_resource_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_link_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ResourceLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_link_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResourceLinkList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_link_proto_goTypes,
		DependencyIndexes: file_resource_link_proto_depIdxs,
		MessageInfos:      file_resource_link_proto_msgTypes,
	}.Build()
	File_resource_link_proto = out.File
	file_resource_link_proto_rawDesc = nil
	file_resource_link_proto_goTypes = nil
	file_resource_link_proto_depIdxs = nil
}
