// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: truck_make.proto

package content_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TruckMake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *TruckMake) Reset() {
	*x = TruckMake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_truck_make_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruckMake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckMake) ProtoMessage() {}

func (x *TruckMake) ProtoReflect() protoreflect.Message {
	mi := &file_truck_make_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckMake.ProtoReflect.Descriptor instead.
func (*TruckMake) Descriptor() ([]byte, []int) {
	return file_truck_make_proto_rawDescGZIP(), []int{0}
}

func (x *TruckMake) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TruckMake) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TruckMake) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TruckMake) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TruckMakesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32        `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	Items []*TruckMake `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (x *TruckMakesList) Reset() {
	*x = TruckMakesList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_truck_make_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruckMakesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckMakesList) ProtoMessage() {}

func (x *TruckMakesList) ProtoReflect() protoreflect.Message {
	mi := &file_truck_make_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckMakesList.ProtoReflect.Descriptor instead.
func (*TruckMakesList) Descriptor() ([]byte, []int) {
	return file_truck_make_proto_rawDescGZIP(), []int{1}
}

func (x *TruckMakesList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TruckMakesList) GetItems() []*TruckMake {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_truck_make_proto protoreflect.FileDescriptor

var file_truck_make_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x6f, 0x0a, 0x09, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x4d, 0x61, 0x6b, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x58, 0x0a, 0x0e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x4d, 0x61, 0x6b,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x72,
	0x75, 0x63, 0x6b, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x1a,
	0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_truck_make_proto_rawDescOnce sync.Once
	file_truck_make_proto_rawDescData = file_truck_make_proto_rawDesc
)

func file_truck_make_proto_rawDescGZIP() []byte {
	file_truck_make_proto_rawDescOnce.Do(func() {
		file_truck_make_proto_rawDescData = protoimpl.X.CompressGZIP(file_truck_make_proto_rawDescData)
	})
	return file_truck_make_proto_rawDescData
}

var file_truck_make_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_truck_make_proto_goTypes = []any{
	(*TruckMake)(nil),      // 0: content_service.TruckMake
	(*TruckMakesList)(nil), // 1: content_service.TruckMakesList
}
var file_truck_make_proto_depIdxs = []int32{
	0, // 0: content_service.TruckMakesList.items:type_name -> content_service.TruckMake
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_truck_make_proto_init() }
func file_truck_make_proto_init() {
	if File_truck_make_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_truck_make_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TruckMake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_truck_make_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TruckMakesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_truck_make_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_truck_make_proto_goTypes,
		DependencyIndexes: file_truck_make_proto_depIdxs,
		MessageInfos:      file_truck_make_proto_msgTypes,
	}.Build()
	File_truck_make_proto = out.File
	file_truck_make_proto_rawDesc = nil
	file_truck_make_proto_goTypes = nil
	file_truck_make_proto_depIdxs = nil
}
