// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: changelog.proto

package event_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyId     string   `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id"`
	Tag           string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag"`
	ItemKey       string   `protobuf:"bytes,3,opt,name=item_key,json=itemKey,proto3" json:"item_key"`
	Changes       []string `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes"`
	CreatedAt     string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy     string   `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	CreatedByName string   `protobuf:"bytes,7,opt,name=created_by_name,json=createdByName,proto3" json:"created_by_name"`
	Id            string   `protobuf:"bytes,8,opt,name=id,proto3" json:"id"`
}

func (x *ChangeLog) Reset() {
	*x = ChangeLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changelog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLog) ProtoMessage() {}

func (x *ChangeLog) ProtoReflect() protoreflect.Message {
	mi := &file_changelog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLog.ProtoReflect.Descriptor instead.
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return file_changelog_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeLog) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ChangeLog) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ChangeLog) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *ChangeLog) GetChanges() []string {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ChangeLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChangeLog) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ChangeLog) GetCreatedByName() string {
	if x != nil {
		return x.CreatedByName
	}
	return ""
}

func (x *ChangeLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangeLogList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ChangeLog `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Count int32        `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
}

func (x *ChangeLogList) Reset() {
	*x = ChangeLogList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changelog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLogList) ProtoMessage() {}

func (x *ChangeLogList) ProtoReflect() protoreflect.Message {
	mi := &file_changelog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLogList.ProtoReflect.Descriptor instead.
func (*ChangeLogList) Descriptor() ([]byte, []int) {
	return file_changelog_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeLogList) GetItems() []*ChangeLog {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ChangeLogList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ChangeLogDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id"`
	ItemKey   string `protobuf:"bytes,3,opt,name=item_key,json=itemKey,proto3" json:"item_key"`
	Tag       string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag"`
}

func (x *ChangeLogDeleteRequest) Reset() {
	*x = ChangeLogDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changelog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLogDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLogDeleteRequest) ProtoMessage() {}

func (x *ChangeLogDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_changelog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLogDeleteRequest.ProtoReflect.Descriptor instead.
func (*ChangeLogDeleteRequest) Descriptor() ([]byte, []int) {
	return file_changelog_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeLogDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeLogDeleteRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ChangeLogDeleteRequest) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *ChangeLogDeleteRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_changelog_proto protoreflect.FileDescriptor

var file_changelog_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0xe7, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x0d, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4c, 0x6f, 0x67, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x74, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74,
	0x65, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x42, 0x18, 0x5a, 0x16, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_changelog_proto_rawDescOnce sync.Once
	file_changelog_proto_rawDescData = file_changelog_proto_rawDesc
)

func file_changelog_proto_rawDescGZIP() []byte {
	file_changelog_proto_rawDescOnce.Do(func() {
		file_changelog_proto_rawDescData = protoimpl.X.CompressGZIP(file_changelog_proto_rawDescData)
	})
	return file_changelog_proto_rawDescData
}

var file_changelog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_changelog_proto_goTypes = []any{
	(*ChangeLog)(nil),              // 0: event_service.ChangeLog
	(*ChangeLogList)(nil),          // 1: event_service.ChangeLogList
	(*ChangeLogDeleteRequest)(nil), // 2: event_service.ChangeLogDeleteRequest
}
var file_changelog_proto_depIdxs = []int32{
	0, // 0: event_service.ChangeLogList.items:type_name -> event_service.ChangeLog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_changelog_proto_init() }
func file_changelog_proto_init() {
	if File_changelog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_changelog_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_changelog_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeLogList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_changelog_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeLogDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_changelog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_changelog_proto_goTypes,
		DependencyIndexes: file_changelog_proto_depIdxs,
		MessageInfos:      file_changelog_proto_msgTypes,
	}.Build()
	File_changelog_proto = out.File
	file_changelog_proto_rawDesc = nil
	file_changelog_proto_goTypes = nil
	file_changelog_proto_depIdxs = nil
}
