info:
  contact: {}
  description: This is a Eld API Gateway server.
  title: Eld API Gateway v1
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
